### PR TITLE
Feature/per 211

### PR DESCRIPTION
**Pull request by JosephJindrich**
You can now load JSON into the UI. Please approve PER-219 first, as that commit seems to be piggybacking.

### CODE REVIEW

**Comment by evanhackett** [comment]
When I try to load `basic_payload.json` (a file that you posted on discord earlier) nothing seems to happen. No errors, but also the scenes don't populate the UI. Nothing is logged to the console either.

**Comment by tnguyen6106** [comment]
I cloned and tested out this PR. I used the basic_payload file and it seems to load all the data from the JSON file just fine. Everything seems to work. However I looked at the checklist of this ticket, it says that there should be an overwrite warning when you load a file that would overwrite the old data, i.e. load a scene with an ID that's already existed. Do you plan on making a separate ticket for that feature?

**Comment by tnguyen6106** [comment]
> I cloned and tested out this PR. I used the basic_payload file and it seems to load all the data from the JSON file just fine. Everything seems to work. However I looked at the checklist of this ticket, it says that there should be an overwrite warning when you load a file that would overwrite the old data, i.e. load a scene with an ID that's already existed. Do you plan on making a separate ticket for that feature?

I just re-read the ticket. It seems that the main task of this ticket is to make sure the data gets "loaded into the UI" so that we actually see the scene list from the file in the UI. The checklist threw me off a little bit there. It seems like the extra functionalities in the checklist should be implemented in separate tickets then.

**Review by tnguyen6106 — APPROVED** [review]
Looks good.

**Comment by evanhackett** [comment]
"The checklist threw me off a little bit there. It seems like the extra functionalities in the checklist should be implemented in separate tickets then."

Well I'm not going to put every single requirement in the title of the trello card. So instead, I put a short title, and then I made the checklist for the sole purposes of communicating what I expect.

So in general, the checklists will probably often contain tasks that seem "extra" I guess. I didn't really think of it as "extra" in this case though, because to me having alerts like that is a core component of this feature. Or at least an alert telling them that they are about to overwrite everything!

Lastly, if you are going to approve a PR that doesn't meet all requirements, you should create the new ticket (for the requirements that were left out). You pointed out a new ticket should be created, but ideally you would actually create it yourself. If you don't have permissions then you should make sure someone else creates it before merging in the PR and closing a ticket that had unfinished requirements. It just seems like things could easily slip though the cracks if we aren't careful about it.

Sorry if the tone is harsh. I think I was just a little annoyed that the creator of the ticket (me) wasn't pinged before it was merged in despite being incomplete. I'm probably just tired and grumpy :)

Overall this is an awesome feature and I'm glad it is done and working. 

Just make sure to create the ticket for the alerts @tnguyen6106 or @JosephJindrich

**Comment by tnguyen6106** [comment]
> 
> 
> "The checklist threw me off a little bit there. It seems like the extra functionalities in the checklist should be implemented in separate tickets then."
> 
> Well I'm not going to put every single requirement in the title of the trello card. So instead, I put a short title, and then I made the checklist for the sole purposes of communicating what I expect.
> 
> So in general, the checklists will probably often contain tasks that seem "extra" I guess. I didn't really think of it as "extra" in this case though, because to me having alerts like that is a core component of this feature. Or at least an alert telling them that they are about to overwrite everything!
> 
> Lastly, if you are going to approve a PR that doesn't meet all requirements, you should create the new ticket (for the requirements that were left out). You pointed out a new ticket should be created, but ideally you would actually create it yourself. If you don't have permissions then you should make sure someone else creates it before merging in the PR and closing a ticket that had unfinished requirements. It just seems like things could easily slip though the cracks if we aren't careful about it.
> 
> Sorry if the tone is harsh. I think I was just a little annoyed that the creator of the ticket (me) wasn't pinged before it was merged in despite being incomplete. I'm probably just tired and grumpy :)
> 
> Overall this is an awesome feature and I'm glad it is done and working.
> 
> Just make sure to create the ticket for the alerts @tnguyen6106 or @JosephJindrich

Sorry for not pinging you first. Thank you for the feed back and I'll keep that in mind. I also just created new tickets in the backlog.

**Pull request merged**
