### PR TITLE
[PER-215] Added Back button

### PR DESCRIPTION
**Pull request by JosephJindrich**
I added a back button to the sceneForm. In order to add a back button to captions, we need a way to tie a scene to a caption, not just a caption to a scene.

### CODE REVIEW

**Comment by evanhackett** [comment]
I feel the button should be on top instead of on bottom. I just feel like usually page navigation buttons are on top. Sometimes you will see websites that have a footer which has navigation links, but those are usually hard links. Something like a back button is almost always up top.

Also, I actually think the link shouldn't even be a button, but rather an anchor tag. If you look at the scene list, you will see that each scene is blue and underlined. This is the browser standard way to signal that those are links. It makes it more intuitive to the user that clicking on them will navigate them to another page. I think buttons that simply perform a page navigation should instead be a link (an anchor tag). 

Not your fault, I should have specified these things in the task on trello.

Lastly, as far as a back button in the caption editor page, you definitely can navigate to the correct scene. Check out `Scene.current`, which refers to the current scene. 

Ok so the TLDR is I would approve this if you make the following changes:

1. make the button an anchor tag (standard link) instead of a button
2. move the link to the top instead of the bottom
3. add the back "button" (link) in the caption editor page as well. Use `Scene.current` to grab the current scene id, which will enable you to route to the correct page.

**Comment by JosephJindrich** [comment]
@evanhackett Scene.current isn't defined when you go into the captionForm. The captionForm is actually quite bugged. I will change the back button and re submit.

**Comment by JosephJindrich** [comment]
@evanhackett Alright I changed the button to a link.

**Comment by evanhackett** [comment]
@JosephJindrich weird, I'll have to look at that later. Scene.current will definitely be the way we do that, since that is exactly the kind of thing it is for. 

For now though, I'll approve this since that can be a separate ticket anyway.

Looks good.

**Review by evanhackett — APPROVED** [review]

**Pull request merged**
