### PR TITLE
Added Duplicate Scene button

### PR DESCRIPTION
**Pull request by plavabe12**
You can now duplicate scenes from the scene list menu and also within a scene.

### CODE REVIEW

**Review by JosephJindrich — CHANGES_REQUESTED** [review]
Nearly perfect, and I actually **really** like the duplicate button, however please make sure to refresh the page after hitting the duplicate button while inside the scene. 

When you duplicate inside, the scene name should change but it doesn't. I think when we clear the cache it does a refresh if you want to check there.

Also @evanhackett I don't think we're supposed to carry over package-lock are we?

**Comment by evanhackett** [comment]
@plavabe12 @JosephJindrich Actually we do carry over package-lock. It is a file we can mostly ignore, but it should be checked in to version control. It's the node_modules folder that we don't want in VC.

Regarding "refreshing the page", what you probably want to do is call one of Mithril's render functions to re-render the page. Although that is surprising it isn't re-rendering automatically, because generally on a DOM event (such as a button click) it will trigger a re-render automatically.

**Comment by evanhackett** [comment]
It is possible that it _is_ re-rendering, but it doesn't have the updated data yet, so it just renders what was already there. I think I've ran into that before.

You'll have to play around with it and see why it isn't immediately re-rendering with the new scene.

**Comment by plavabe12** [comment]
@JosephJindrich @evanhackett the page does get refreshed but it's a bug within our code. Mithril assumes we aren't changing the page so it doesn't update the dom. To fix this problem it would involve refactoring the code to include [mithril keys](https://mithril.js.org/keys.html). A temporary bug fix would be to redirect the user into scenes then the actual scene itself.

The package-lock file is automatically generated by npm every time you run `npm i`  and installs the new dependencies.

**Comment by plavabe12** [comment]
The document.location.reload function works. But in the future it would be better if mithril could redraw the page automatically.

**Review by JosephJindrich — APPROVED** [review]
Looking good

**Pull request merged**
