### PR TITLE
add caption text preview with colors and attributes to scene form.

### PR DESCRIPTION
**Pull request by evanhackett**

### CODE REVIEW

**Review by JosephJindrich — CHANGES_REQUESTED** [review]
Since you decided to do a preview, I have a few suggestions about the way it displays.

1. Make sure you have white text and Black background as the defaults if there is no settings, as that is how it's going to appear.
2. The Blue is more purple than the blue in the captions. If you look at uploads you can see what the colors look like when they are being displayed. 
3. It's difficult to see white without any background, could you darken the tickets a bit to it appears more? a darker grey should work as dark grey isn't one of the colors.
4. You need to cap the amount of characters you show. Otherwise it ends up looking like this.
image
5. Can you add "Caption String Preview: " before you show the caption string as well, so the user knows what they are looking at?
6. Now that we see the caption string preview, you should be able to click on it and go to the caption page. Clicking anywhere on the card should do this as well.

**Comment by JosephJindrich** [comment]
@evanhackett Is it possible to add a toggle as well? While this is great for a regular user, some of the color combinations are difficult to see, and might be hard for the visually impaired. If there is a way to toggle on and off the settings and make them regular black that would be awesome.

**Comment by evanhackett** [comment]
@JosephJindrich 

1. Is black background actually the default, or is "None" the default? I want to display it in a way that tells the user what they have selected. If black background is the default, then we should initialize all captions by setting the background to black.

2. I did it the easy way by just setting the css using the color word itself. So "blue" and "magenta" etc. are css keywords, which made it super easy to set the colors based off the value from the forms. I could have a switch statement that maps colors to RGB values, that way we could get closer to the actual colors. But I also wasn't sure if CEA-608 actually specifies what the colors are supposed to look like. What if that is an implementation detail, and every different video player could display slightly different colors? So I decided to just go with the easier route in terms of the code, since I didn't think getting the exact color as it would appear in live would matter.

3. That makes sense, I can do that.

4. I actually kind of like that it will wrap down and you can see the entire thing. I don't think it ruins the UI to see the entire caption. I personally prefer it. For example:
Screenshot from 2019-11-17 12-47-33

I think that looks good. However, I do admit that your screenshot did not look good. It looks like it was extending out of the bounds instead of wrapping, which is strange. So we need to do something about that. But I don't like the idea of truncating (well maybe at a certain limit) because I actually like seeing the whole thing and I think it looks good when it wraps.

5. Yeah that makes sense.

6. Yeah that makes sense. It actually used to behave that way when I first made it, but once I added the delete button I had to change that behavior. Since the button is within the container, adding a click event on the entire container was causing issues with the delete button. But I think there are ways around that, I'll just have to play around with it.

**Comment by JosephJindrich** [comment]
@evanhackett I think one of the reasons yours wrapped is because there's a line break, where in mine there was not.

**Comment by JosephJindrich** [comment]
@evanhackett  The black background is the default. it's the 0x0 value of the background colors. I believe that is correct but @albicant could shed light on this.

**Comment by evanhackett** [comment]
Yes I can add a toggle. Good idea.

And yeah it will break on spaces between words. I just tested it with a bunch of chars with no spaces, and it did not break to a new line. I'll have to think about the best way to handle that.

**Comment by albicant** [comment]
> 
> 
> @evanhackett The black background is the default. it's the 0x0 value of the background colors. I believe that is correct but @albicant could shed light on this.

@JosephJindrich The black background is the default if background is not set. If the Control Command for the background colors is being called, then the default background color (in my implementation of the function) would be "no background". Otherwise black background would be set by adding 1110 to the second byte.

**Comment by evanhackett** [comment]
Ok @JosephJindrich, I fixed most of the concerns.

set default background color to black, and default foreground color to white.
made background darker grey so white text is easier to see
added "Caption String Preview: " before showing the caption
added a toggle to toggle on/off the styling.
now wrapping text that doesn't have spaces

**Review by JosephJindrich — DISMISSED** [review]
Looks great

**Review by JosephJindrich — APPROVED** [review]

**Pull request merged**
