### PR TITLE
PER-410 adding unit tests for caption string utilities

### PR DESCRIPTION
**Pull request by Markobozic**

### CODE REVIEW

**Review by JosephJindrich — CHANGES_REQUESTED** [review]
I ran your tests, and I got an error. We should never push a unit test that is failing.
image
Also we have a tutorial on how to run tests in our README, You need to update that with how to run these tests.

**Comment by Markobozic** [comment]
It's funky but this is correct in failing, the function is not correct. I will have to merge the PR for per 393 to make it passing. Also how are you running the tests, i can't run all test files at once

**Comment by JosephJindrich** [comment]
In order to run it I added `sys.path.append("../../..")` and then just went into test and ran `python  .\caption_string_utility_test.py` and it ran. I'll hold off on approving this until I've tested it with PER-393

**Comment by JosephJindrich** [comment]
All tests passed after a rebase. 
image
I still have to add 
```
import sys
sys.path.append("../../..")
```
In order to get it to work. I'm not sure why. I will pass after the README has been updated.

**Comment by Markobozic** [comment]
i'm writing more tests atm and then will update the readme, but i'm still not sure how to run a suite of tests. are you running `python3 unittest` to execute the tests or just running the python interpreter on the test file?

**Comment by JosephJindrich** [comment]
in the second image you can see what I call. I just went into tests and did 
`python .\caption_string_utility_test.py`

**Comment by Markobozic** [comment]
Can you follow the README instructions for running and see if the testsuite runs

**Comment by Markobozic** [comment]
try: `export PYTHONPATH="${PYTHONPATH}:path/to/Perception/"` is you're getting import errors

**Review by JosephJindrich — APPROVED** [review]

**Pull request merged**
